@server = http://localhost:4004
@auth = Authorization: Basic alice:


### FreightOrder
# @name FreightOrder_GET
GET {{server}}/odata/v4/freightorder/FreightOrder
{{auth}}


### FreightOrder
# @name FreightOrder_POST
POST {{server}}/odata/v4/freightorder/FreightOrder
Content-Type: application/json
{{auth}}

{
  "TransportationOrderUUID": "20354454-4791-4d82-a1c2-4e10fa1224bb",
  "TransportationOrder": "tationOrder-20354454",
  "TransportationOrderType": "4454",
  "TransportationOrderCategory": "54",
  "TransportationShippingType": "454",
  "TransportationMode": "54",
  "TransportationModeCategory": "4",
  "CarrierUUID": "20354454-2ea2-4ed0-8cc7-ce57b4579b5b",
  "Carrier": "r-20354454",
  "StandardCarrierAlphaCode": "4454",
  "TranspOrdExecutingCarrierUUID": "20354454-0033-430f-80b0-9a2c9959c050",
  "TranspOrdExecutingCarrier": "r-20354454",
  "ShipperUUID": "20354454-473b-47f0-84b1-292a6418d26d",
  "Shipper": "r-20354454",
  "ShipperAddressID": "ShipperAddressID-20354454",
  "ConsigneeUUID": "20354454-64ad-43b4-be5a-ec32fb3109d1",
  "Consignee": "e-20354454",
  "ConsigneeAddressID": "ConsigneeAddressID-20354454",
  "TranspPurgOrg": "20354454",
  "TranspPurgOrgExtID": "urgOrgExtID-20354454",
  "TranspPurgGroup": "20354454",
  "TranspPurgGroupExtID": "gGroupExtID-20354454",
  "PurgOrgCompanyCode": "4454",
  "CarrierAccountNumber": "umber-20354454",
  "TranspMeansOfTransport": "t-20354454",
  "TranspOrdPartnerReference": "TranspOrdPartnerReference-20354454",
  "TranspOrdResponsiblePerson": "son-20354454",
  "TranspOrdHasMltplExectgPties": true,
  "TranspOrdInvoicingCarrierLevel": "54",
  "TranspOrdLifeCycleStatus": "54",
  "TranspOrderSubcontrgSts": "54",
  "TransportationOrderConfSts": "54",
  "TransportationOrderExecSts": "54",
  "TranspOrdGoodsMovementStatus": "4",
  "TranspOrdWhseProcessingStatus": "4",
  "TranspOrderDngrsGdsSts": "4",
  "TranspOrdExecutionIsBlocked": true,
  "TransportationOrderCrtnType": "54",
  "CreatedByUser": "ser-20354454",
  "CreationDateTime": "2004-05-01T00:00:00.000Z",
  "LastChangedByUser": "ser-20354454",
  "ChangedDateTime": "2018-01-23T00:00:00.000Z",
  "FreightOrderItems": [
    {
      "TransportationOrderItemUUID": "50170145-ccc5-4c45-ae88-62b88fee746b",
      "TranspOrdItem": "em-5017014",
      "TranspOrdItemType": "7014",
      "TranspOrdItemCategory": "014",
      "TranspOrdItemParentItemUUID": "5017014c-f6c8-4bfb-a3dd-6ee3fc2b6883",
      "TranspOrdItemDesc": "TranspOrdItemDesc-5017014",
      "IsMainCargoItem": true,
      "TranspOrdItemSorting": "017014",
      "SourceStopUUID": "50170146-3c10-4ebf-b474-56c3cb4f4d23",
      "DestinationStopUUID": "50170147-3ab9-491f-998c-eac5449bea58",
      "ShipperUUID": "50170143-767f-414e-a3f7-ff6f304c876d",
      "Shipper": "er-5017014",
      "ShipperAddressID": "ShipperAddressID-5017014",
      "ConsigneeUUID": "5017014c-06cb-4648-a85c-becc7e2f5630",
      "Consignee": "ee-5017014",
      "ConsigneeAddressID": "ConsigneeAddressID-5017014",
      "FreightUnitUUID": "5017014f-ddc5-4a8e-bc27-cb723a75942f",
      "PredecessorTransportationOrder": "5017014d-44ee-40cc-94fa-1806abac07e9",
      "TranspBaseDocument": "TranspBaseDocument-5017014",
      "TranspBaseDocumentType": "17014",
      "TranspBaseDocumentItem": "em-5017014",
      "TranspBaseDocumentItemType": "17014",
      "TransportationEquipmentGroup": "014",
      "TransportationEquipmentType": "pe-5017014",
      "TranspEquipmentIsShipperOwned": true,
      "TranspEquipmentPlateNumber": "tPlateNumber-5017014",
      "TranspEquipRegistrationCountry": "014",
      "TranspEquipCapacityLength": 33.243,
      "TranspEquipCapacityWidth": 15.216,
      "TranspEquipCapacityHeight": 75.102,
      "TranspEquipCapacityUnit": "014",
      "TranspEquipCapacityWeight": 97.12140631,
      "TranspEquipCapacityWeightUnit": "014",
      "TranspEquipCapacityVolume": 82.14154777,
      "TranspEquipCapacityVolumeUnit": "014",
      "TranspOrdItemPackageID": "TranspOrdItemPackageID-5017014",
      "ProductUUID": "50170142-8517-4aab-9212-f5e10db14a4d",
      "ProductID": "ProductID-5017014",
      "MaterialFreightGroup": "-5017014",
      "TransportationGroup": "7014",
      "TranspOrdItmMinTemp": 29.97,
      "TranspOrdItmMaxTemp": 73.11,
      "TranspOrdItemTemperatureUnit": "014",
      "TranspOrdItemQuantity": 67.7377809,
      "TranspOrdItemQuantityUnit": "014",
      "TranspOrdItemGrossWeight": 13.7109946,
      "TranspOrdItemGrossWeightUnit": "014",
      "TranspOrdItemGrossVolume": 38.11861953,
      "TranspOrdItemGrossVolumeUnit": "014",
      "TranspOrdItemNetWeight": 41.16030614,
      "TranspOrdItemNetWeightUnit": "014"
    },
    {
      "TransportationOrderItemUUID": "50170157-3210-41d6-ac7d-d6d01430295a",
      "TranspOrdItem": "em-5017015",
      "TranspOrdItemType": "7015",
      "TranspOrdItemCategory": "015",
      "TranspOrdItemParentItemUUID": "50170156-fbcd-4227-82cb-4587699a66d1",
      "TranspOrdItemDesc": "TranspOrdItemDesc-5017015",
      "IsMainCargoItem": false,
      "TranspOrdItemSorting": "017015",
      "SourceStopUUID": "50170150-9e48-4f5e-a406-be32448bcbd4",
      "DestinationStopUUID": "5017015f-4376-425c-9180-41037c64961d",
      "ShipperUUID": "5017015b-ec27-475c-9704-67e78a2167e8",
      "Shipper": "er-5017015",
      "ShipperAddressID": "ShipperAddressID-5017015",
      "ConsigneeUUID": "50170155-46ae-4fae-9139-1df20562f1f1",
      "Consignee": "ee-5017015",
      "ConsigneeAddressID": "ConsigneeAddressID-5017015",
      "FreightUnitUUID": "50170159-4f1c-49fa-8cbb-4c03cbe48ac7",
      "PredecessorTransportationOrder": "5017015c-1418-4105-b657-dc2d81cf5ae0",
      "TranspBaseDocument": "TranspBaseDocument-5017015",
      "TranspBaseDocumentType": "17015",
      "TranspBaseDocumentItem": "em-5017015",
      "TranspBaseDocumentItemType": "17015",
      "TransportationEquipmentGroup": "015",
      "TransportationEquipmentType": "pe-5017015",
      "TranspEquipmentIsShipperOwned": false,
      "TranspEquipmentPlateNumber": "tPlateNumber-5017015",
      "TranspEquipRegistrationCountry": "015",
      "TranspEquipCapacityLength": 70.234,
      "TranspEquipCapacityWidth": 54.2,
      "TranspEquipCapacityHeight": 49.273,
      "TranspEquipCapacityUnit": "015",
      "TranspEquipCapacityWeight": 37.21121001,
      "TranspEquipCapacityWeightUnit": "015",
      "TranspEquipCapacityVolume": 88.14605149,
      "TranspEquipCapacityVolumeUnit": "015",
      "TranspOrdItemPackageID": "TranspOrdItemPackageID-5017015",
      "ProductUUID": "50170159-5ba1-48aa-8418-e4b94f5d064a",
      "ProductID": "ProductID-5017015",
      "MaterialFreightGroup": "-5017015",
      "TransportationGroup": "7015",
      "TranspOrdItmMinTemp": 11.25,
      "TranspOrdItmMaxTemp": 71.32,
      "TranspOrdItemTemperatureUnit": "015",
      "TranspOrdItemQuantity": 25.12794687,
      "TranspOrdItemQuantityUnit": "015",
      "TranspOrdItemGrossWeight": 83.27484884,
      "TranspOrdItemGrossWeightUnit": "015",
      "TranspOrdItemGrossVolume": 73.16730906,
      "TranspOrdItemGrossVolumeUnit": "015",
      "TranspOrdItemNetWeight": 77.20449011,
      "TranspOrdItemNetWeightUnit": "015"
    }
  ]
}


### FreightOrder
# @name FreightOrder_PATCH
PATCH {{server}}/odata/v4/freightorder/FreightOrder/20354454-4791-4d82-a1c2-4e10fa1224bb
Content-Type: application/json
{{auth}}

{
  "TransportationOrderUUID": "20354454-4791-4d82-a1c2-4e10fa1224bb",
  "TransportationOrder": "tationOrder-20354454",
  "TransportationOrderType": "4454",
  "TransportationOrderCategory": "54",
  "TransportationShippingType": "454",
  "TransportationMode": "54",
  "TransportationModeCategory": "4",
  "CarrierUUID": "20354454-2ea2-4ed0-8cc7-ce57b4579b5b",
  "Carrier": "r-20354454",
  "StandardCarrierAlphaCode": "4454",
  "TranspOrdExecutingCarrierUUID": "20354454-0033-430f-80b0-9a2c9959c050",
  "TranspOrdExecutingCarrier": "r-20354454",
  "ShipperUUID": "20354454-473b-47f0-84b1-292a6418d26d",
  "Shipper": "r-20354454",
  "ShipperAddressID": "ShipperAddressID-20354454",
  "ConsigneeUUID": "20354454-64ad-43b4-be5a-ec32fb3109d1",
  "Consignee": "e-20354454",
  "ConsigneeAddressID": "ConsigneeAddressID-20354454",
  "TranspPurgOrg": "20354454",
  "TranspPurgOrgExtID": "urgOrgExtID-20354454",
  "TranspPurgGroup": "20354454",
  "TranspPurgGroupExtID": "gGroupExtID-20354454",
  "PurgOrgCompanyCode": "4454",
  "CarrierAccountNumber": "umber-20354454",
  "TranspMeansOfTransport": "t-20354454",
  "TranspOrdPartnerReference": "TranspOrdPartnerReference-20354454",
  "TranspOrdResponsiblePerson": "son-20354454",
  "TranspOrdHasMltplExectgPties": true,
  "TranspOrdInvoicingCarrierLevel": "54",
  "TranspOrdLifeCycleStatus": "54",
  "TranspOrderSubcontrgSts": "54",
  "TransportationOrderConfSts": "54",
  "TransportationOrderExecSts": "54",
  "TranspOrdGoodsMovementStatus": "4",
  "TranspOrdWhseProcessingStatus": "4",
  "TranspOrderDngrsGdsSts": "4",
  "TranspOrdExecutionIsBlocked": true,
  "TransportationOrderCrtnType": "54",
  "CreatedByUser": "ser-20354454",
  "CreationDateTime": "2004-05-01T00:00:00.000Z",
  "LastChangedByUser": "ser-20354454",
  "ChangedDateTime": "2018-01-23T00:00:00.000Z",
  "FreightOrderItems": [
    {
      "TransportationOrderItemUUID": "50170145-ccc5-4c45-ae88-62b88fee746b",
      "TranspOrdItem": "em-5017014",
      "TranspOrdItemType": "7014",
      "TranspOrdItemCategory": "014",
      "TranspOrdItemParentItemUUID": "5017014c-f6c8-4bfb-a3dd-6ee3fc2b6883",
      "TranspOrdItemDesc": "TranspOrdItemDesc-5017014",
      "IsMainCargoItem": true,
      "TranspOrdItemSorting": "017014",
      "SourceStopUUID": "50170146-3c10-4ebf-b474-56c3cb4f4d23",
      "DestinationStopUUID": "50170147-3ab9-491f-998c-eac5449bea58",
      "ShipperUUID": "50170143-767f-414e-a3f7-ff6f304c876d",
      "Shipper": "er-5017014",
      "ShipperAddressID": "ShipperAddressID-5017014",
      "ConsigneeUUID": "5017014c-06cb-4648-a85c-becc7e2f5630",
      "Consignee": "ee-5017014",
      "ConsigneeAddressID": "ConsigneeAddressID-5017014",
      "FreightUnitUUID": "5017014f-ddc5-4a8e-bc27-cb723a75942f",
      "PredecessorTransportationOrder": "5017014d-44ee-40cc-94fa-1806abac07e9",
      "TranspBaseDocument": "TranspBaseDocument-5017014",
      "TranspBaseDocumentType": "17014",
      "TranspBaseDocumentItem": "em-5017014",
      "TranspBaseDocumentItemType": "17014",
      "TransportationEquipmentGroup": "014",
      "TransportationEquipmentType": "pe-5017014",
      "TranspEquipmentIsShipperOwned": true,
      "TranspEquipmentPlateNumber": "tPlateNumber-5017014",
      "TranspEquipRegistrationCountry": "014",
      "TranspEquipCapacityLength": 33.243,
      "TranspEquipCapacityWidth": 15.216,
      "TranspEquipCapacityHeight": 75.102,
      "TranspEquipCapacityUnit": "014",
      "TranspEquipCapacityWeight": 97.12140631,
      "TranspEquipCapacityWeightUnit": "014",
      "TranspEquipCapacityVolume": 82.14154777,
      "TranspEquipCapacityVolumeUnit": "014",
      "TranspOrdItemPackageID": "TranspOrdItemPackageID-5017014",
      "ProductUUID": "50170142-8517-4aab-9212-f5e10db14a4d",
      "ProductID": "ProductID-5017014",
      "MaterialFreightGroup": "-5017014",
      "TransportationGroup": "7014",
      "TranspOrdItmMinTemp": 29.97,
      "TranspOrdItmMaxTemp": 73.11,
      "TranspOrdItemTemperatureUnit": "014",
      "TranspOrdItemQuantity": 67.7377809,
      "TranspOrdItemQuantityUnit": "014",
      "TranspOrdItemGrossWeight": 13.7109946,
      "TranspOrdItemGrossWeightUnit": "014",
      "TranspOrdItemGrossVolume": 38.11861953,
      "TranspOrdItemGrossVolumeUnit": "014",
      "TranspOrdItemNetWeight": 41.16030614,
      "TranspOrdItemNetWeightUnit": "014"
    },
    {
      "TransportationOrderItemUUID": "50170157-3210-41d6-ac7d-d6d01430295a",
      "TranspOrdItem": "em-5017015",
      "TranspOrdItemType": "7015",
      "TranspOrdItemCategory": "015",
      "TranspOrdItemParentItemUUID": "50170156-fbcd-4227-82cb-4587699a66d1",
      "TranspOrdItemDesc": "TranspOrdItemDesc-5017015",
      "IsMainCargoItem": false,
      "TranspOrdItemSorting": "017015",
      "SourceStopUUID": "50170150-9e48-4f5e-a406-be32448bcbd4",
      "DestinationStopUUID": "5017015f-4376-425c-9180-41037c64961d",
      "ShipperUUID": "5017015b-ec27-475c-9704-67e78a2167e8",
      "Shipper": "er-5017015",
      "ShipperAddressID": "ShipperAddressID-5017015",
      "ConsigneeUUID": "50170155-46ae-4fae-9139-1df20562f1f1",
      "Consignee": "ee-5017015",
      "ConsigneeAddressID": "ConsigneeAddressID-5017015",
      "FreightUnitUUID": "50170159-4f1c-49fa-8cbb-4c03cbe48ac7",
      "PredecessorTransportationOrder": "5017015c-1418-4105-b657-dc2d81cf5ae0",
      "TranspBaseDocument": "TranspBaseDocument-5017015",
      "TranspBaseDocumentType": "17015",
      "TranspBaseDocumentItem": "em-5017015",
      "TranspBaseDocumentItemType": "17015",
      "TransportationEquipmentGroup": "015",
      "TransportationEquipmentType": "pe-5017015",
      "TranspEquipmentIsShipperOwned": false,
      "TranspEquipmentPlateNumber": "tPlateNumber-5017015",
      "TranspEquipRegistrationCountry": "015",
      "TranspEquipCapacityLength": 70.234,
      "TranspEquipCapacityWidth": 54.2,
      "TranspEquipCapacityHeight": 49.273,
      "TranspEquipCapacityUnit": "015",
      "TranspEquipCapacityWeight": 37.21121001,
      "TranspEquipCapacityWeightUnit": "015",
      "TranspEquipCapacityVolume": 88.14605149,
      "TranspEquipCapacityVolumeUnit": "015",
      "TranspOrdItemPackageID": "TranspOrdItemPackageID-5017015",
      "ProductUUID": "50170159-5ba1-48aa-8418-e4b94f5d064a",
      "ProductID": "ProductID-5017015",
      "MaterialFreightGroup": "-5017015",
      "TransportationGroup": "7015",
      "TranspOrdItmMinTemp": 11.25,
      "TranspOrdItmMaxTemp": 71.32,
      "TranspOrdItemTemperatureUnit": "015",
      "TranspOrdItemQuantity": 25.12794687,
      "TranspOrdItemQuantityUnit": "015",
      "TranspOrdItemGrossWeight": 83.27484884,
      "TranspOrdItemGrossWeightUnit": "015",
      "TranspOrdItemGrossVolume": 73.16730906,
      "TranspOrdItemGrossVolumeUnit": "015",
      "TranspOrdItemNetWeight": 77.20449011,
      "TranspOrdItemNetWeightUnit": "015"
    }
  ]
}


### FreightOrder
# @name FreightOrder_DELETE
DELETE {{server}}/odata/v4/freightorder/FreightOrder/20354454-4791-4d82-a1c2-4e10fa1224bb
Content-Type: application/json
{{auth}}


### FreightOrderItem
# @name FreightOrderItem_GET
GET {{server}}/odata/v4/freightorder/FreightOrderItem
{{auth}}


### FreightOrderItem
# @name FreightOrderItem_POST
POST {{server}}/odata/v4/freightorder/FreightOrderItem
Content-Type: application/json
{{auth}}

{
  "TransportationOrderItemUUID": "50170145-ccc5-4c45-ae88-62b88fee746b",
  "TranspOrdItem": "em-5017014",
  "TranspOrdItemType": "7014",
  "TranspOrdItemCategory": "014",
  "TranspOrdItemParentItemUUID": "5017014c-f6c8-4bfb-a3dd-6ee3fc2b6883",
  "TranspOrdItemDesc": "TranspOrdItemDesc-5017014",
  "IsMainCargoItem": true,
  "TranspOrdItemSorting": "017014",
  "SourceStopUUID": "50170146-3c10-4ebf-b474-56c3cb4f4d23",
  "DestinationStopUUID": "50170147-3ab9-491f-998c-eac5449bea58",
  "ShipperUUID": "50170143-767f-414e-a3f7-ff6f304c876d",
  "Shipper": "er-5017014",
  "ShipperAddressID": "ShipperAddressID-5017014",
  "ConsigneeUUID": "5017014c-06cb-4648-a85c-becc7e2f5630",
  "Consignee": "ee-5017014",
  "ConsigneeAddressID": "ConsigneeAddressID-5017014",
  "FreightUnitUUID": "5017014f-ddc5-4a8e-bc27-cb723a75942f",
  "PredecessorTransportationOrder": "5017014d-44ee-40cc-94fa-1806abac07e9",
  "TranspBaseDocument": "TranspBaseDocument-5017014",
  "TranspBaseDocumentType": "17014",
  "TranspBaseDocumentItem": "em-5017014",
  "TranspBaseDocumentItemType": "17014",
  "TransportationEquipmentGroup": "014",
  "TransportationEquipmentType": "pe-5017014",
  "TranspEquipmentIsShipperOwned": true,
  "TranspEquipmentPlateNumber": "tPlateNumber-5017014",
  "TranspEquipRegistrationCountry": "014",
  "TranspEquipCapacityLength": 33.243,
  "TranspEquipCapacityWidth": 15.216,
  "TranspEquipCapacityHeight": 75.102,
  "TranspEquipCapacityUnit": "014",
  "TranspEquipCapacityWeight": 97.12140631,
  "TranspEquipCapacityWeightUnit": "014",
  "TranspEquipCapacityVolume": 82.14154777,
  "TranspEquipCapacityVolumeUnit": "014",
  "TranspOrdItemPackageID": "TranspOrdItemPackageID-5017014",
  "ProductUUID": "50170142-8517-4aab-9212-f5e10db14a4d",
  "ProductID": "ProductID-5017014",
  "MaterialFreightGroup": "-5017014",
  "TransportationGroup": "7014",
  "TranspOrdItmMinTemp": 29.97,
  "TranspOrdItmMaxTemp": 73.11,
  "TranspOrdItemTemperatureUnit": "014",
  "TranspOrdItemQuantity": 67.7377809,
  "TranspOrdItemQuantityUnit": "014",
  "TranspOrdItemGrossWeight": 13.7109946,
  "TranspOrdItemGrossWeightUnit": "014",
  "TranspOrdItemGrossVolume": 38.11861953,
  "TranspOrdItemGrossVolumeUnit": "014",
  "TranspOrdItemNetWeight": 41.16030614,
  "TranspOrdItemNetWeightUnit": "014"
}


### FreightOrderItem
# @name FreightOrderItem_PATCH
PATCH {{server}}/odata/v4/freightorder/FreightOrderItem/50170145-ccc5-4c45-ae88-62b88fee746b
Content-Type: application/json
{{auth}}

{
  "TransportationOrderItemUUID": "50170145-ccc5-4c45-ae88-62b88fee746b",
  "TranspOrdItem": "em-5017014",
  "TranspOrdItemType": "7014",
  "TranspOrdItemCategory": "014",
  "TranspOrdItemParentItemUUID": "5017014c-f6c8-4bfb-a3dd-6ee3fc2b6883",
  "TranspOrdItemDesc": "TranspOrdItemDesc-5017014",
  "IsMainCargoItem": true,
  "TranspOrdItemSorting": "017014",
  "SourceStopUUID": "50170146-3c10-4ebf-b474-56c3cb4f4d23",
  "DestinationStopUUID": "50170147-3ab9-491f-998c-eac5449bea58",
  "ShipperUUID": "50170143-767f-414e-a3f7-ff6f304c876d",
  "Shipper": "er-5017014",
  "ShipperAddressID": "ShipperAddressID-5017014",
  "ConsigneeUUID": "5017014c-06cb-4648-a85c-becc7e2f5630",
  "Consignee": "ee-5017014",
  "ConsigneeAddressID": "ConsigneeAddressID-5017014",
  "FreightUnitUUID": "5017014f-ddc5-4a8e-bc27-cb723a75942f",
  "PredecessorTransportationOrder": "5017014d-44ee-40cc-94fa-1806abac07e9",
  "TranspBaseDocument": "TranspBaseDocument-5017014",
  "TranspBaseDocumentType": "17014",
  "TranspBaseDocumentItem": "em-5017014",
  "TranspBaseDocumentItemType": "17014",
  "TransportationEquipmentGroup": "014",
  "TransportationEquipmentType": "pe-5017014",
  "TranspEquipmentIsShipperOwned": true,
  "TranspEquipmentPlateNumber": "tPlateNumber-5017014",
  "TranspEquipRegistrationCountry": "014",
  "TranspEquipCapacityLength": 33.243,
  "TranspEquipCapacityWidth": 15.216,
  "TranspEquipCapacityHeight": 75.102,
  "TranspEquipCapacityUnit": "014",
  "TranspEquipCapacityWeight": 97.12140631,
  "TranspEquipCapacityWeightUnit": "014",
  "TranspEquipCapacityVolume": 82.14154777,
  "TranspEquipCapacityVolumeUnit": "014",
  "TranspOrdItemPackageID": "TranspOrdItemPackageID-5017014",
  "ProductUUID": "50170142-8517-4aab-9212-f5e10db14a4d",
  "ProductID": "ProductID-5017014",
  "MaterialFreightGroup": "-5017014",
  "TransportationGroup": "7014",
  "TranspOrdItmMinTemp": 29.97,
  "TranspOrdItmMaxTemp": 73.11,
  "TranspOrdItemTemperatureUnit": "014",
  "TranspOrdItemQuantity": 67.7377809,
  "TranspOrdItemQuantityUnit": "014",
  "TranspOrdItemGrossWeight": 13.7109946,
  "TranspOrdItemGrossWeightUnit": "014",
  "TranspOrdItemGrossVolume": 38.11861953,
  "TranspOrdItemGrossVolumeUnit": "014",
  "TranspOrdItemNetWeight": 41.16030614,
  "TranspOrdItemNetWeightUnit": "014"
}


### FreightOrderItem
# @name FreightOrderItem_DELETE
DELETE {{server}}/odata/v4/freightorder/FreightOrderItem/50170145-ccc5-4c45-ae88-62b88fee746b
Content-Type: application/json
{{auth}}
